language: python
dist: xenial
sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.8-dev" # 3.8 development branch
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

virtualenv:
  system_site_packages: false

services:
  - postgresql

install:
  - pip install psycopg2
  - pip install anyblok
  - pip install flake8
  - pip install coverage
  - pip install nose
  - pip install WebTest
  - pip install coveralls
  - python setup.py develop

env:
  global:
    - ANYBLOK_DATABASE_NAME=travis_ci_test
    - ANYBLOK_DATABASE_DRIVER=postgresql
    - ANYBLOK_DATABASE_USER=postgres

script:
  - flake8 anyblok_pyramid --ignore F999
  - psql -c 'create database travis_ci_test;' -U postgres
  - nosetests anyblok_pyramid/tests -v -s --with-coverage --cover-package=anyblok_pyramid
  - psql -c 'drop database travis_ci_test;' -U postgres
  - anyblok_createdb --install-all-bloks
  - nosetests anyblok_pyramid/bloks --with-anyblok-bloks -v -s --with-coverage --cover-package=anyblok_pyramid
  
after_success:
  coveralls
